//
// Created by Usuario on 3/11/2025.
//

#ifndef INC_9_PRACTICA_POLLIMORFISMOSALARIO_ABRAHAM21587_EMPLEADO_H
#define INC_9_PRACTICA_POLLIMORFISMOSALARIO_ABRAHAM21587_EMPLEADO_H


class empleado {
};


#endif //INC_9_PRACTICA_POLLIMORFISMOSALARIO_ABRAHAM21587_EMPLEADO_H